name: ci-min

on:
  push:
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4            # récupère ton code
      - uses: actions/setup-java@v4          # installe JDK 21 sur le runner
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run API smoke
        env:
          API_BASE_URL: https://automationexercise.com/api
        run: mvn -B -pl api-tests -am test

  ui:
    runs-on: ubuntu-latest
    services:
      selenium:                              # Chrome headless à côté du job
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Run UI smoke (RemoteWebDriver)
        env:
          BASE_URL: https://automationexercise.com
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: mvn -B -pl ui-tests -am test